/**
 * build-amxd.mjs - write a Max for Live .amxd, headless. No Max in the loop.
 *
 * The container format is undocumented but simple, reverse-engineered from
 * devices saved by Max 8/9:
 *
 *   'ampf' <u32le 4> <'aaaa'|'mmmm'|'iiii'>   audio / midi / instrument
 *   'meta' <u32le 4> <u32le 7>
 *   'ptch' <u32le size-to-EOF>
 *     'mx@c' <u32be 16> <u32be 0> <u32be 16 + payload sizes (excl. dlst)>
 *     <patcher JSON> <dependency payloads...>
 *     'dlst' <u32be chunk size incl. header>   directory: one 'dire' per file
 *
 * The device type comes from the patcher's project.amxdtype. The device is
 * written "frozen" with wrapper.js embedded (the same shape Max produces when
 * you freeze), so Max never resolves wrapper.js via a search path. The internal
 * main-patcher name is set to the output file's basename.
 *
 * Usage:
 *   node scripts/build-amxd.mjs <patcher.json> <wrapper.js> <ui.html> <output.amxd> [extraFile ...]
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "acorn";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const [patcherPath, wrapperPath, uiPath, outPath, ...extraPaths] = process.argv.slice(2);
if (!patcherPath || !wrapperPath || !uiPath || !outPath) {
	console.error("usage: node scripts/build-amxd.mjs <patcher.json> <wrapper.js> <ui.html> <output.amxd> [extraFile ...]");
	process.exit(1);
}

const patcherJson = readFileSync(patcherPath, "utf8");
const wrapperJs = readFileSync(wrapperPath, "utf8");

// The ES5 gate again, at the last possible moment: this is the byte sequence
// that actually ships, so this is where refusing to package matters.
try {
	parse(wrapperJs, { ecmaVersion: 5 });
} catch (e) {
	console.error(`build-amxd: ${path.basename(wrapperPath)} is not valid ES5: ${e.message}`);
	process.exit(1);
}

/**
 * Self-extracting payload.
 *
 * Frozen dependencies live in Max's virtual filesystem and never exist on
 * disk, so jweb (Chromium) cannot load the UI we shipped inside our own
 * device. But wrapper.js ALWAYS runs - so append the UI to it as base64 and
 * let it write a real file next to the .amxd on first load. See
 * resolveUiUrl()/extractPayload() in wrapper/wrapper.ts.
 */
const UI_NAME = "ui.html";
const uiHtml = readFileSync(uiPath); // Buffer - exact bytes

function payloadJs(varPrefix, name, buf) {
	const CHUNK = 30000; // multiple of 3 -> each chunk is padding-free base64
	const chunks = [];
	for (let i = 0; i < buf.length; i += CHUNK) {
		chunks.push(JSON.stringify(buf.subarray(i, i + CHUNK).toString("base64")));
	}
	return (
		`\n// ---- generated by build-amxd.mjs: embedded ${varPrefix} payload ----\n` +
		`var ${varPrefix}_NAME = ${JSON.stringify(name)};\n` +
		`var ${varPrefix}_BYTES = ${buf.length};\n` +
		`var ${varPrefix}_B64 = [\n${chunks.join(",\n")}\n];\n`
	);
}

// Build stamp: the wrapper posts it at load and the UI renders it, so a device
// instance can always tell you WHICH build it is. Live embeds a copy of the
// device in the set, so stale instances are a real debugging trap - this is
// what makes them visible instead of mysterious.
const { version } = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const stamp = `${version} ${new Date().toISOString()}`;

let wrapperData = `var BUILD_STAMP = ${JSON.stringify(stamp)};\n` + wrapperJs;
wrapperData += payloadJs("UI_PAYLOAD", UI_NAME, uiHtml);

// 'aaaa' audio effect / 'mmmm' MIDI effect / 'iiii' instrument.
const AMXD_TYPES = { 0x61616161: "aaaa", 0x6d6d6d6d: "mmmm", 0x69696969: "iiii" };
const amxdtype = JSON.parse(patcherJson).patcher?.project?.amxdtype;
const deviceType = AMXD_TYPES[amxdtype];
if (!deviceType) {
	console.error(`build-amxd: unknown project.amxdtype ${amxdtype} in ${patcherPath}`);
	process.exit(1);
}

const macDate = Math.floor(Date.now() / 1000) + 2082844800; // secs since 1904-01-01

const files = [
	{ type: "JSON", name: path.basename(outPath), data: Buffer.from(patcherJson, "utf8"), flag: 0x11 },
	{ type: "TEXT", name: "wrapper.js", data: Buffer.from(wrapperData, "utf8"), flag: 0 },
];
for (const p of extraPaths) {
	const isJson = p.endsWith(".maxpat") || p.endsWith(".json");
	files.push({ type: isJson ? "JSON" : "TEXT", name: path.basename(p), data: readFileSync(p), flag: 0 });
}

function u32be(n) {
	const b = Buffer.alloc(4);
	b.writeUInt32BE(n >>> 0);
	return b;
}
function u32le(n) {
	const b = Buffer.alloc(4);
	b.writeUInt32LE(n >>> 0);
	return b;
}
function field(tag, payload) {
	return Buffer.concat([Buffer.from(tag, "latin1"), u32be(8 + payload.length), payload]);
}
function paddedName(name) {
	const raw = Buffer.from(name + "\0", "latin1");
	return Buffer.concat([raw, Buffer.alloc((4 - (raw.length % 4)) % 4)]);
}

// Payload region: the patcher JSON first, at offset 16 (right after mx@c).
let offset = 16;
const entries = [];
for (const f of files) {
	f.offset = offset;
	offset += f.data.length;
	entries.push(
		field(
			"dire",
			Buffer.concat([
				field("type", Buffer.from(f.type, "latin1")),
				field("fnam", paddedName(f.name)),
				field("sz32", u32be(f.data.length)),
				field("of32", u32be(f.offset)),
				field("vers", u32be(0)),
				field("flag", u32be(f.flag)),
				field("mdat", u32be(macDate)),
			]),
		),
	);
}

const payload = Buffer.concat(files.map((f) => f.data));
const mxc = Buffer.concat([Buffer.from("mx@c", "latin1"), u32be(16), u32be(0), u32be(16 + payload.length)]);
const dlst = field("dlst", Buffer.concat(entries));
const ptchBody = Buffer.concat([mxc, payload, dlst]);

const amxd = Buffer.concat([
	Buffer.from("ampf", "latin1"),
	u32le(4),
	Buffer.from(deviceType, "latin1"),
	Buffer.from("meta", "latin1"),
	u32le(4),
	u32le(7),
	Buffer.from("ptch", "latin1"),
	u32le(ptchBody.length),
	ptchBody,
]);

writeFileSync(outPath, amxd);
console.log(`build-amxd: ${path.relative(root, outPath)} (${deviceType}, ${amxd.length} bytes)`);
